// Package prompt generates an archscope-style AI context document for the
// set of fake source files produced by fakecodegen.
package prompt

import (
	"fmt"
	"math/rand/v2"
	"path/filepath"
	"sort"
	"strings"
)

// FileInfo describes one generated file.
type FileInfo struct {
	Path  string   // relative path inside the output folder
	Lines int      // total line count
	Decls []string // top-level declaration names (functions)
}

// Config holds the parameters for prompt generation.
type Config struct {
	Lang       string     // "go" | "py"
	FolderName string     // base name of the output folder (used as module name)
	Files      []FileInfo // generated files, in any order
	Rng        *rand.Rand
}

var goTechStack = []string{
	"net/http", "encoding/json", "context", "sync", "io", "os", "log/slog",
	"database/sql", "crypto/tls", "time", "math/rand", "bufio", "strings",
	"Gin", "Echo", "Chi", "Fiber", "GORM", "sqlx", "Cobra", "Viper",
	"Prometheus", "OpenTelemetry", "Zap", "Zerolog", "testify", "gRPC",
	"Protocol Buffers", "Redis", "PostgreSQL", "MongoDB", "Kafka", "NATS",
}

var pyTechStack = []string{
	"asyncio", "dataclasses", "typing", "pathlib", "json", "os", "sys",
	"logging", "datetime", "collections", "functools", "itertools",
	"FastAPI", "Flask", "Django", "SQLAlchemy", "Pydantic", "Celery",
	"pytest", "aiohttp", "httpx", "Redis", "PostgreSQL", "MongoDB",
	"NumPy", "pandas", "Prometheus", "OpenTelemetry", "Kafka", "boto3",
}

var goAuthors = []string{
	"Alice Chen", "Bob Kim", "Carlos Ruiz", "Diana Lee", "Ethan Park",
	"Fiona Wang", "Grace Liu", "Henry Zhang", "Iris Nakamura", "Jake Brown",
}

var pyAuthors = []string{
	"Anna Kovac", "Ben Torres", "Clara Singh", "David Müller", "Elena Petrov",
	"Felix Okafor", "Gina Yamamoto", "Hassan Ali", "Isla Campbell", "Jan Nowak",
}

func langLabel(lang string) string {
	switch lang {
	case "go":
		return "Go"
	case "py":
		return "Python"
	}
	return lang
}

func pickN(rng *rand.Rand, items []string, n int) []string {
	if n >= len(items) {
		return items
	}
	picked := make([]string, len(items))
	copy(picked, items)
	rng.Shuffle(len(picked), func(i, j int) { picked[i], picked[j] = picked[j], picked[i] })
	return picked[:n]
}

// Generate returns the archscope-format prompt document as a string.
func Generate(cfg Config) string {
	label := langLabel(cfg.Lang)

	// Aggregate stats
	totalLines := 0
	totalDecls := 0
	for _, f := range cfg.Files {
		totalLines += f.Lines
		totalDecls += len(f.Decls)
	}

	// Sort files by line count descending for Key Files section
	sorted := make([]FileInfo, len(cfg.Files))
	copy(sorted, cfg.Files)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Lines > sorted[j].Lines
	})
	keyFiles := sorted
	if len(keyFiles) > 15 {
		keyFiles = keyFiles[:15]
	}

	// Pick tech stack
	var techPool []string
	switch cfg.Lang {
	case "go":
		techPool = goTechStack
	default:
		techPool = pyTechStack
	}
	techCount := cfg.Rng.IntN(5) + 3
	tech := pickN(cfg.Rng, techPool, techCount)
	sort.Strings(tech)

	// Fake git stats
	totalCommits := cfg.Rng.IntN(90) + 10
	typedCommits := cfg.Rng.IntN(totalCommits)

	var authorPool []string
	switch cfg.Lang {
	case "go":
		authorPool = goAuthors
	default:
		authorPool = pyAuthors
	}
	authorCount := cfg.Rng.IntN(3) + 1
	authors := pickN(cfg.Rng, authorPool, authorCount)

	// Hot files: pick top files by random change count
	type hotFile struct {
		path    string
		changes int
	}
	var hotFiles []hotFile
	for _, f := range cfg.Files {
		hotFiles = append(hotFiles, hotFile{
			path:    f.Path,
			changes: cfg.Rng.IntN(8) + 1,
		})
	}
	sort.Slice(hotFiles, func(i, j int) bool {
		return hotFiles[i].changes > hotFiles[j].changes
	})
	if len(hotFiles) > 15 {
		hotFiles = hotFiles[:15]
	}

	var b strings.Builder

	fmt.Fprintf(&b, "# %s — Architecture Context\n\n", label)
	b.WriteString("This document was generated by fakecodegen. ")
	b.WriteString("Use it as context when asking an AI assistant questions about this codebase.\n\n")

	b.WriteString("## Overview\n\n")
	fmt.Fprintf(&b, "- **Platform:** %s\n", label)
	fmt.Fprintf(&b, "- **Files:** %d  |  **Lines:** %s  |  **Declarations:** %d\n",
		len(cfg.Files), fmtNum(totalLines), totalDecls)
	fmt.Fprintf(&b, "- **Modules:** %s\n\n", cfg.FolderName)

	b.WriteString("## Tech Stack\n\n")
	b.WriteString(strings.Join(tech, " · "))
	b.WriteString("\n\n")

	b.WriteString("## Key Files\n\n")
	for _, f := range keyFiles {
		declStr := ""
		if len(f.Decls) > 0 {
			decls := f.Decls
			if len(decls) > 12 {
				decls = decls[:12]
			}
			declStr = " — " + strings.Join(decls, ", ")
		}
		fmt.Fprintf(&b, "- `%s` (%d lines)%s\n",
			filepath.ToSlash(f.Path), f.Lines, declStr)
	}
	b.WriteByte('\n')

	b.WriteString("## Git Stats\n\n")
	fmt.Fprintf(&b, "- **Total commits:** %d  |  **Typed:** %d/%d\n",
		totalCommits, typedCommits, totalCommits)
	fmt.Fprintf(&b, "- **Top authors:** %s\n", strings.Join(authors, ", "))
	b.WriteString("- **Hot files (by change count):**\n")
	for _, hf := range hotFiles {
		fmt.Fprintf(&b, "  - %s (%d changes)\n", filepath.ToSlash(hf.path), hf.changes)
	}
	b.WriteByte('\n')

	return b.String()
}

func fmtNum(n int) string {
	s := fmt.Sprintf("%d", n)
	if n < 1000 {
		return s
	}
	var out []byte
	for i, ch := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, byte(ch))
	}
	return string(out)
}
