package render

import (
	"fmt"
	"math/rand/v2"
	"path/filepath"
	"sort"
	"strings"

	"github.com/exey/fakecodegen/internal/ast"
)

// All params are typed as int so they can safely appear in integer arithmetic
// expressions generated by GenIntExpr without type-mismatch errors.
// For domain-aware (TypedParams) functions the renderer uses TypedParam.Type
// instead, marking non-int params as used with `_ = param`.
var goParamTypes = []string{"int"}

// goReturnTypesDefault is used when FuncDef.ReturnType is empty.
var goReturnTypesDefault = []string{"int64", "string", "bool", "error", "any"}

// GoRenderer renders AST to Go source.
type GoRenderer struct {
	w              IndentWriter
	inFunction     bool
	currentRetType string
	pkg            string
	imports        map[string]bool // tracks stdlib packages needed
}

func NewGoRenderer(filePath string) *GoRenderer {
	return &GoRenderer{
		w:       NewIndentWriter("\t"),
		pkg:     deriveGoPackage(filePath),
		imports: make(map[string]bool),
	}
}

// deriveGoPackage returns a valid Go package identifier from a file path.
// "internal/config/cfg.go" → "config", "auth.go" → "generated".
func deriveGoPackage(filePath string) string {
	dir := filepath.Dir(filepath.ToSlash(filePath))
	if dir == "." || dir == "" {
		return "generated"
	}
	base := filepath.Base(dir)
	// Lowercase, strip non-alpha chars
	var b strings.Builder
	for _, r := range strings.ToLower(base) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	pkg := b.String()
	if pkg == "" || (pkg[0] >= '0' && pkg[0] <= '9') {
		return "generated"
	}
	return pkg
}

func randGoParamType() string { return goParamTypes[rand.IntN(len(goParamTypes))] }
func randGoReturn() string    { return goReturnTypesDefault[rand.IntN(len(goReturnTypesDefault))] }

// trackTypeImports scans a type string for package-qualified names (e.g.
// "context.Context", "time.Time") and adds the package to r.imports.
func (r *GoRenderer) trackTypeImports(typ string) {
	for _, part := range strings.Fields(typ) {
		// Strip slice/pointer prefixes.
		part = strings.TrimLeft(part, "[]*")
		if dot := strings.IndexByte(part, '.'); dot > 0 {
			r.imports[part[:dot]] = true
		}
	}
}

func (r *GoRenderer) renderExpr(expr ast.Expression) string {
	switch e := expr.(type) {
	case ast.ArithExpr:
		if e.Op == ast.Power {
			return fmt.Sprintf("(%s + %s)", r.renderExpr(e.Left), r.renderExpr(e.Right))
		}
		return fmt.Sprintf("(%s %s %s)", r.renderExpr(e.Left), goArithOp(e.Op), r.renderExpr(e.Right))
	case ast.UnaryExpr:
		switch e.Op {
		case ast.Negate:
			return fmt.Sprintf("(-%s)", r.renderExpr(e.Operand))
		default:
			return fmt.Sprintf("(^%s)", r.renderExpr(e.Operand))
		}
	case ast.BoolExpr:
		op := "&&"
		if e.Op == ast.Or {
			op = "||"
		}
		return fmt.Sprintf("(%s %s %s)", r.renderExpr(e.Left), op, r.renderExpr(e.Right))
	case ast.CondExpr:
		return fmt.Sprintf("(%s %s %s)", r.renderExpr(e.Left), renderCondOp(e.Op), r.renderExpr(e.Right))
	case ast.FuncCallExpr:
		return fmt.Sprintf("%s()", e.Name)
	case ast.VarExpr:
		return e.Name
	case ast.StringLit:
		return fmt.Sprintf("%q", e.Value)
	case ast.IntLit:
		return fmt.Sprintf("%d", e.Value)
	case ast.FloatLit:
		return fmt.Sprintf("%.4f", e.Value)
	case ast.BoolLit:
		if e.Value {
			return "true"
		}
		return "false"
	}
	return "_"
}

// typedReturnExpr emits a return value that matches the current function's
// declared return type, ensuring the generated Go code compiles.
func (r *GoRenderer) typedReturnExpr(val ast.Expression) string {
	switch r.currentRetType {
	case "int64":
		switch v := val.(type) {
		case ast.IntLit:
			return fmt.Sprintf("int64(%d)", v.Value)
		case ast.VarExpr:
			return fmt.Sprintf("int64(%s)", v.Name)
		default:
			return "int64(0)"
		}
	case "string":
		// Use fmt.Sprintf only when we have a concrete value to embed.
		switch v := val.(type) {
		case ast.VarExpr:
			r.imports["fmt"] = true
			return fmt.Sprintf("fmt.Sprintf(\"result: %%d\", %s)", v.Name)
		case ast.IntLit:
			r.imports["fmt"] = true
			return fmt.Sprintf("fmt.Sprintf(\"result: %%d\", %d)", v.Value)
		default:
			return `"ok"`
		}
	case "bool":
		switch v := val.(type) {
		case ast.BoolLit:
			if v.Value {
				return "true"
			}
			return "false"
		case ast.VarExpr:
			return fmt.Sprintf("(%s > 0)", v.Name)
		default:
			return "false"
		}
	case "error":
		// 50/50: nil or fmt.Errorf
		if rand.IntN(2) == 0 {
			return "nil"
		}
		r.imports["fmt"] = true
		switch v := val.(type) {
		case ast.VarExpr:
			return fmt.Sprintf("fmt.Errorf(\"operation failed for %%d\", %s)", v.Name)
		default:
			return `fmt.Errorf("operation failed")`
		}
	default: // "any" — any expression is valid
		return r.renderExpr(val)
	}
}

func (r *GoRenderer) renderBlock(block []ast.Statement, out *strings.Builder) {
	// Collect names declared at this block level (either := assignments,
	// inner closures, or helper call results) so we can emit "_ = name" to
	// satisfy Go's "declared and not used" rule.
	// FuncDef names at the package level are handled by Go itself and must NOT
	// be included here.
	var blockDecls []string
	for _, stmt := range block {
		switch s := stmt.(type) {
		case ast.Assignment:
			if s.IsDecl {
				blockDecls = append(blockDecls, s.Name)
			}
		case ast.FuncDef:
			// Closures rendered as `name := func() T {...}` are local variables
			// and must be marked used.  This branch is only reached when we are
			// already inside a function (r.inFunction == true).
			if r.inFunction {
				blockDecls = append(blockDecls, s.Name)
			}
		case ast.HelperCallStmt:
			blockDecls = append(blockDecls, s.Result)
		}
	}

	emitDecls := func() {
		for _, name := range blockDecls {
			r.w.Line(out, fmt.Sprintf("_ = %s", name))
		}
	}

	if len(block) == 0 {
		return
	}

	// Emit "_ = name" cleanup BEFORE the last statement when it terminates
	// control flow (return or switch-with-default), so that:
	//  - the return remains the final statement (Go's missing-return check)
	//  - no cleanup appears after an unreachable point
	// For all other blocks emit cleanup AFTER all statements.
	lastStmt := block[len(block)-1]
	_, lastIsReturn := lastStmt.(ast.ReturnStmt)
	_, lastIsSwitch := lastStmt.(ast.SwitchStmt)
	emitBeforeLast := lastIsReturn || lastIsSwitch

	for i, stmt := range block {
		if emitBeforeLast && i == len(block)-1 {
			emitDecls()
		}
		r.renderStmt(stmt, out)
	}

	if !emitBeforeLast {
		emitDecls()
	}
}

func (r *GoRenderer) renderStmt(stmt ast.Statement, out *strings.Builder) {
	switch s := stmt.(type) {
	case ast.Assignment:
		if !r.inFunction {
			// Package-level: always a var declaration.
			r.w.Line(out, fmt.Sprintf("var %s = %s", s.Name, r.renderExpr(s.Value)))
		} else if s.IsDecl {
			// New local variable.
			r.w.Line(out, fmt.Sprintf("%s := %s", s.Name, r.renderExpr(s.Value)))
		} else {
			// Reassignment: use _ = expr to avoid type-mismatch between the
			// variable's inferred type and the new value's type.
			r.w.Line(out, fmt.Sprintf("_ = %s", r.renderExpr(s.Value)))
		}

	case ast.IfStmt:
		r.w.Line(out, fmt.Sprintf("if %s {", r.renderExpr(s.Cond)))
		r.w.Inc()
		r.renderBlock(s.Then, out)
		r.w.Dec()
		if len(s.Else) > 0 {
			r.w.Line(out, "} else {")
			r.w.Inc()
			r.renderBlock(s.Else, out)
			r.w.Dec()
		}
		r.w.Line(out, "}")

	case ast.WhileStmt:
		r.w.Line(out, fmt.Sprintf("for %s {", r.renderExpr(s.Cond)))
		r.w.Inc()
		r.renderBlock(s.Body, out)
		r.w.Dec()
		r.w.Line(out, "}")

	case ast.ForStmt:
		// Range is always an integer expression (ensured by generator).
		// Wrap in int() to handle VarExpr that might be any type at runtime.
		rangeStr := r.renderIntRange(s.Range)
		r.w.Line(out, fmt.Sprintf("for %s := range %s {", s.Var, rangeStr))
		r.w.Inc()
		// Always mark the loop variable as used so that body statements which
		// happen not to reference it don't trigger "declared and not used".
		r.w.Line(out, fmt.Sprintf("_ = %s", s.Var))
		r.renderBlock(s.Body, out)
		r.w.Dec()
		r.w.Line(out, "}")

	case ast.FuncDef:
		retType := s.ReturnType
		if retType == "" {
			retType = randGoReturn()
		}
		prevRetType := r.currentRetType
		r.currentRetType = retType
		prev := r.inFunction
		r.inFunction = true

		if prev {
			// Inside a function: emit as a closure (named functions can't be
			// declared inside other functions in Go).
			r.w.Line(out, fmt.Sprintf("%s := func() %s {", s.Name, retType))
			r.w.Inc()
			r.renderBlock(s.Body, out)
			r.w.Dec()
			r.w.Line(out, "}")
		} else {
			// Package-level function.
			paramStr := r.renderFuncParams(s)
			r.w.Line(out, fmt.Sprintf("func %s(%s) %s {", s.Name, paramStr, retType))
			r.w.Inc()
			// Mark non-int typed params as used at top of function.
			if len(s.TypedParams) > 0 {
				for _, tp := range s.TypedParams {
					if tp.Type != "int" {
						r.w.Line(out, fmt.Sprintf("_ = %s", tp.Name))
					}
				}
			}
			r.renderBlock(s.Body, out)
			r.w.Dec()
			r.w.Line(out, "}")
			r.w.Blank(out)
		}

		r.inFunction = prev
		r.currentRetType = prevRetType

	case ast.ReturnStmt:
		r.w.Line(out, fmt.Sprintf("return %s", r.typedReturnExpr(s.Value)))

	case ast.ExprStmt:
		// Prefer calling functions as statements; otherwise use _ = expr
		if fc, ok := s.Expr.(ast.FuncCallExpr); ok {
			r.w.Line(out, fmt.Sprintf("%s()", fc.Name))
		} else {
			r.w.Line(out, fmt.Sprintf("_ = %s", r.renderExpr(s.Expr)))
		}

	case ast.CommentStmt:
		r.w.Line(out, fmt.Sprintf("// %s", s.Text))

	case ast.SwitchStmt:
		r.w.Line(out, fmt.Sprintf("switch %s {", s.Tag))
		for _, c := range s.Cases {
			r.w.Line(out, fmt.Sprintf("case %d:", c.Value))
			r.w.Inc()
			r.renderBlock(c.Body, out)
			r.w.Dec()
		}
		if len(s.Default) > 0 {
			r.w.Line(out, "default:")
			r.w.Inc()
			r.renderBlock(s.Default, out)
			r.w.Dec()
		}
		r.w.Line(out, "}")

	case ast.DeferStmt:
		r.imports["log"] = true
		r.w.Line(out, fmt.Sprintf("defer log.Println(%q)", s.Text))

	case ast.HelperCallStmt:
		args := strings.Join(s.Args, ", ")
		r.w.Line(out, fmt.Sprintf("%s := %s(%s)", s.Result, s.Name, args))

	case ast.StructDecl:
		r.w.Line(out, fmt.Sprintf("type %s struct {", s.Name))
		r.w.Inc()
		for _, f := range s.Fields {
			r.trackTypeImports(f.Type)
			r.w.Line(out, fmt.Sprintf("%s %s", f.Name, f.Type))
		}
		r.w.Dec()
		r.w.Line(out, "}")
		r.w.Blank(out)

	case ast.InterfaceDecl:
		r.w.Line(out, fmt.Sprintf("type %s interface {", s.Name))
		r.w.Inc()
		for _, m := range s.Methods {
			for _, pt := range m.ParamTypes {
				r.trackTypeImports(pt)
			}
			r.trackTypeImports(m.ReturnType)
			params := strings.Join(m.ParamTypes, ", ")
			r.w.Line(out, fmt.Sprintf("%s(%s) %s", m.Name, params, m.ReturnType))
		}
		r.w.Dec()
		r.w.Line(out, "}")
		r.w.Blank(out)
	}
}

// renderFuncParams returns the parameter list string for a function definition.
func (r *GoRenderer) renderFuncParams(fd ast.FuncDef) string {
	if len(fd.TypedParams) > 0 {
		parts := make([]string, len(fd.TypedParams))
		for i, tp := range fd.TypedParams {
			parts[i] = fmt.Sprintf("%s %s", tp.Name, tp.Type)
		}
		return strings.Join(parts, ", ")
	}
	// Legacy: all params typed as int.
	var parts []string
	for _, p := range fd.ParamNames {
		parts = append(parts, fmt.Sprintf("%s %s", p, randGoParamType()))
	}
	return strings.Join(parts, ", ")
}

// renderIntRange ensures the range expression compiles as an integer.
func (r *GoRenderer) renderIntRange(expr ast.Expression) string {
	switch e := expr.(type) {
	case ast.IntLit:
		if e.Value <= 0 {
			return "1"
		}
		return fmt.Sprintf("%d", e.Value)
	case ast.VarExpr:
		return fmt.Sprintf("int(%s)", e.Name)
	case ast.ArithExpr:
		return fmt.Sprintf("(%s %s %s)", r.renderIntRange(e.Left), goArithOp(e.Op), r.renderIntRange(e.Right))
	default:
		return "10"
	}
}

// goLocalConsts are name/value pairs injected as local consts inside init()
// to reduce magic numbers without causing package-level redeclaration errors.
var goLocalConsts = []struct{ name, value string }{
	{"maxRetries", "3"},
	{"bufSize", "4096"},
	{"timeout", "30"},
	{"maxConn", "100"},
	{"pageSize", "50"},
	{"defaultPort", "8080"},
	{"maxWorkers", "16"},
	{"batchSize", "64"},
	{"cacheSize", "256"},
	{"retryDelay", "5"},
	{"maxDepth", "10"},
	{"minLen", "1"},
	{"maxLen", "512"},
	{"defaultTTL", "3600"},
	{"flushInterval", "60"},
}

// RenderProgram renders a full Go source file.
// Top-level FuncDefs, StructDecls, and InterfaceDecls are emitted at package
// level.  All other statements are collected into an init() function prefixed
// with a small const block of named configuration values.
func (r *GoRenderer) RenderProgram(program []ast.Statement) string {
	var out strings.Builder
	fmt.Fprintf(&out, "package %s\n\n", r.pkg)

	// Separate top-level declarations from init() statements.
	var topDecls []ast.Statement
	var initStmts []ast.Statement
	for _, stmt := range program {
		switch stmt.(type) {
		case ast.FuncDef, ast.StructDecl, ast.InterfaceDecl:
			topDecls = append(topDecls, stmt)
		default:
			initStmts = append(initStmts, stmt)
		}
	}

	// Render top-level declarations (imports will be collected during this pass).
	var declBuf strings.Builder
	for _, stmt := range topDecls {
		r.inFunction = false
		r.renderStmt(stmt, &declBuf)
	}

	// Also do a dry-run of init stmts into a temp buffer to collect imports.
	var initBuf strings.Builder
	if len(initStmts) > 0 {
		r.inFunction = true
		r.w.Inc()
		initBuf.WriteString("\tconst (\n")
		used := make(map[string]bool)
		count := 3 + rand.IntN(3)
		for _, c := range rand.Perm(len(goLocalConsts)) {
			if len(used) >= count {
				break
			}
			entry := goLocalConsts[c]
			if !used[entry.name] {
				used[entry.name] = true
				fmt.Fprintf(&initBuf, "\t\t%s = %s\n", entry.name, entry.value)
			}
		}
		initBuf.WriteString("\t)\n")
		r.renderBlock(initStmts, &initBuf)
		r.w.Dec()
		r.inFunction = false
	}

	// Emit imports if any were collected.
	if len(r.imports) > 0 {
		pkgs := make([]string, 0, len(r.imports))
		for pkg := range r.imports {
			pkgs = append(pkgs, pkg)
		}
		sort.Strings(pkgs)
		out.WriteString("import (\n")
		for _, pkg := range pkgs {
			fmt.Fprintf(&out, "\t%q\n", pkg)
		}
		out.WriteString(")\n\n")
	}

	out.WriteString(declBuf.String())

	if len(initStmts) > 0 {
		out.WriteString("func init() {\n")
		out.WriteString(initBuf.String())
		out.WriteString("}\n")
	}

	return out.String()
}

func goArithOp(op ast.ArithmeticOperator) string {
	switch op {
	case ast.Add:
		return "+"
	case ast.Subtract:
		return "-"
	case ast.Multiply:
		return "*"
	case ast.Divide:
		return "/"
	case ast.Modulo:
		return "%"
	case ast.BitwiseAnd:
		return "&"
	case ast.BitwiseOr:
		return "|"
	case ast.BitwiseXor:
		return "^"
	case ast.ShiftLeft:
		return "<<"
	case ast.ShiftRight:
		return ">>"
	}
	return "+"
}
